apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lms
type: Opaque
stringData:
  AUTH_SECRET: "replace-me"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/lms_db?schema=public"
