export const PERMISSION_DEFINITIONS = [
  { key: "user.view", category: "User" },
  { key: "user.create", category: "User" },
  { key: "user.update", category: "User" },
  { key: "user.delete", category: "User" },
  { key: "user.assign_role", category: "User" },
  { key: "student.view", category: "Student" },
  { key: "student.create", category: "Student" },
  { key: "student.update", category: "Student" },
  { key: "student.delete", category: "Student" },
  { key: "staff.view", category: "Staff" },
  { key: "staff.create", category: "Staff" },
  { key: "staff.update", category: "Staff" },
  { key: "staff.delete", category: "Staff" },
  { key: "class.view", category: "Class" },
  { key: "class.create", category: "Class" },
  { key: "class.update", category: "Class" },
  { key: "class.delete", category: "Class" },
  { key: "section.manage", category: "Class" },
  { key: "attendance.view", category: "Attendance" },
  { key: "attendance.mark", category: "Attendance" },
  { key: "attendance.update", category: "Attendance" },
  { key: "fee.view", category: "Finance" },
  { key: "fee.collect", category: "Finance" },
  { key: "fee.update", category: "Finance" },
  { key: "fee.report", category: "Finance" },
  { key: "subject.manage", category: "Academic" },
  { key: "exam.manage", category: "Academic" },
  { key: "result.manage", category: "Academic" },
  { key: "payroll.view", category: "Payroll" },
  { key: "payroll.process", category: "Payroll" },
  { key: "settings.view", category: "Settings" },
  { key: "settings.update", category: "Settings" },
  { key: "role.view", category: "Role" },
  { key: "role.create", category: "Role" },
  { key: "role.update", category: "Role" },
  { key: "role.delete", category: "Role" },
  { key: "permission.assign", category: "Role" },
] as const;

export type PermissionKey = (typeof PERMISSION_DEFINITIONS)[number]["key"];

export const PERMISSIONS = {
  userView: "user.view",
  userCreate: "user.create",
  userUpdate: "user.update",
  userDelete: "user.delete",
  userAssignRole: "user.assign_role",
  studentView: "student.view",
  studentCreate: "student.create",
  studentUpdate: "student.update",
  studentDelete: "student.delete",
  staffView: "staff.view",
  staffCreate: "staff.create",
  staffUpdate: "staff.update",
  staffDelete: "staff.delete",
  classView: "class.view",
  classCreate: "class.create",
  classUpdate: "class.update",
  classDelete: "class.delete",
  sectionManage: "section.manage",
  attendanceView: "attendance.view",
  attendanceMark: "attendance.mark",
  attendanceUpdate: "attendance.update",
  feeView: "fee.view",
  feeCollect: "fee.collect",
  feeUpdate: "fee.update",
  feeReport: "fee.report",
  subjectManage: "subject.manage",
  examManage: "exam.manage",
  resultManage: "result.manage",
  payrollView: "payroll.view",
  payrollProcess: "payroll.process",
  settingsView: "settings.view",
  settingsUpdate: "settings.update",
  roleView: "role.view",
  roleCreate: "role.create",
  roleUpdate: "role.update",
  roleDelete: "role.delete",
  permissionAssign: "permission.assign",
} as const satisfies Record<string, PermissionKey>;

export const DEFAULT_SYSTEM_ROLES = [
  "Admin Staff",
  "Teacher",
  "HR",
  "Accountant",
  "Receptionist",
  "Student",
] as const;
